### PR TITLE
Add .npmignore

### PR DESCRIPTION
**Pull request by officialpiyush**
# Additions

* Added a `.npmignore` file which excludes the src directory and tsconfig.json, tslint.json files to be uploaded to npm

### CODE REVIEW

**Comment by Anish-Shobith** [comment]
So basically it's only gonna publish dist folder or the out dir to the npm so it would reduce the package size is what i am thinking right now

**Comment by officialpiyush** [comment]
Yes now you get it. You previously thought that this wont push those files to GitHub too :joy:

**Comment by Anish-Shobith** [comment]
> Yes now you get it. You previously thought that this wont push those files to GitHub too

I thought it was gitignore xd

**Comment by WarHammer414** [comment]
already added one but haven't pushed to github

**Pull request closed without merging**
